/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Dial_H
#define Dial_H

#include "thrift/TDispatchProcessor.h"
#include "dialrpc_types.h"

namespace rpc { namespace dial { namespace yamutech { namespace com {

class DialIf {
 public:
  virtual ~DialIf() {}
  virtual RetCode::type systemCommand(const SysCommand::type cmdType) = 0;
  virtual RetCode::type addHealthGroup(const std::string& groupName, const std::string& policyName) = 0;
  virtual RetCode::type delHealthGroup(const std::string& groupName, const std::string& policyName) = 0;
  virtual RetCode::type addHealthRecord(const std::string& groupName, const std::vector<DialRecord> & records) = 0;
  virtual RetCode::type delHealthRecord(const std::string& groupName, const std::vector<DialRecord> & records) = 0;
  virtual RetCode::type addHealthPolicy(const HealthPolicyInfo& policy) = 0;
  virtual RetCode::type modHealthPolicy(const HealthPolicyInfo& policy) = 0;
  virtual RetCode::type delHealthPolicy(const HealthPolicyInfo& policy) = 0;
  virtual RetCode::type addDialServer(const ObjectId& rid, const IpAddr& ip, const DialServerType::type typ) = 0;
  virtual RetCode::type delDialServer(const ObjectId& rid) = 0;
  virtual RetCode::type addNginxGroup(const std::string& groupName, const std::string& policyName) = 0;
  virtual RetCode::type delNginxGroup(const std::string& groupName, const std::string& policyName) = 0;
  virtual RetCode::type addNginxServer(const std::string& groupName, const std::vector<DialNginxServer> & servers) = 0;
  virtual RetCode::type delNginxServer(const std::string& groupName, const std::vector<DialNginxServer> & servers) = 0;
  virtual void heartBeat(HeartBeatState& _return) = 0;
  virtual RetCode::type setServerState(const bool enable) = 0;
  virtual RetCode::type addSnmpGroupInfo(const SnmpGroupInfo& snmp) = 0;
  virtual RetCode::type delSnmpGroupInfo(const std::string& snmp) = 0;
  virtual RetCode::type addSnmpProcessInfo(const std::string& snmp, const std::string& processname) = 0;
  virtual RetCode::type delSnmpProcessInfo(const std::string& snmp, const std::string& processname) = 0;
  virtual RetCode::type addIpSec(const SysIpSec& ipsec, const int32_t interval) = 0;
  virtual RetCode::type delIpSec(const std::string& ipsecid) = 0;
  virtual RetCode::type addDcInfo(const DcInfo& dc) = 0;
  virtual RetCode::type delDcInfo(const std::string& id) = 0;
};

class DialIfFactory {
 public:
  typedef DialIf Handler;

  virtual ~DialIfFactory() {}

  virtual DialIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(DialIf* /* handler */) = 0;
};

class DialIfSingletonFactory : virtual public DialIfFactory {
 public:
  DialIfSingletonFactory(const boost::shared_ptr<DialIf>& iface) : iface_(iface) {}
  virtual ~DialIfSingletonFactory() {}

  virtual DialIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(DialIf* /* handler */) {}

 protected:
  boost::shared_ptr<DialIf> iface_;
};

class DialNull : virtual public DialIf {
 public:
  virtual ~DialNull() {}
  RetCode::type systemCommand(const SysCommand::type /* cmdType */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type addHealthGroup(const std::string& /* groupName */, const std::string& /* policyName */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type delHealthGroup(const std::string& /* groupName */, const std::string& /* policyName */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type addHealthRecord(const std::string& /* groupName */, const std::vector<DialRecord> & /* records */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type delHealthRecord(const std::string& /* groupName */, const std::vector<DialRecord> & /* records */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type addHealthPolicy(const HealthPolicyInfo& /* policy */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type modHealthPolicy(const HealthPolicyInfo& /* policy */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type delHealthPolicy(const HealthPolicyInfo& /* policy */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type addDialServer(const ObjectId& /* rid */, const IpAddr& /* ip */, const DialServerType::type /* typ */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type delDialServer(const ObjectId& /* rid */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type addNginxGroup(const std::string& /* groupName */, const std::string& /* policyName */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type delNginxGroup(const std::string& /* groupName */, const std::string& /* policyName */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type addNginxServer(const std::string& /* groupName */, const std::vector<DialNginxServer> & /* servers */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type delNginxServer(const std::string& /* groupName */, const std::vector<DialNginxServer> & /* servers */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  void heartBeat(HeartBeatState& /* _return */) {
    return;
  }
  RetCode::type setServerState(const bool /* enable */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type addSnmpGroupInfo(const SnmpGroupInfo& /* snmp */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type delSnmpGroupInfo(const std::string& /* snmp */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type addSnmpProcessInfo(const std::string& /* snmp */, const std::string& /* processname */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type delSnmpProcessInfo(const std::string& /* snmp */, const std::string& /* processname */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type addIpSec(const SysIpSec& /* ipsec */, const int32_t /* interval */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type delIpSec(const std::string& /* ipsecid */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type addDcInfo(const DcInfo& /* dc */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
  RetCode::type delDcInfo(const std::string& /* id */) {
    RetCode::type _return = (RetCode::type)0;
    return _return;
  }
};

typedef struct _Dial_systemCommand_args__isset {
  _Dial_systemCommand_args__isset() : cmdType(false) {}
  bool cmdType;
} _Dial_systemCommand_args__isset;

class Dial_systemCommand_args {
 public:

  Dial_systemCommand_args() : cmdType((SysCommand::type)0) {
  }

  virtual ~Dial_systemCommand_args() throw() {}

  SysCommand::type cmdType;

  _Dial_systemCommand_args__isset __isset;

  void __set_cmdType(const SysCommand::type val) {
    cmdType = val;
  }

  bool operator == (const Dial_systemCommand_args & rhs) const
  {
    if (!(cmdType == rhs.cmdType))
      return false;
    return true;
  }
  bool operator != (const Dial_systemCommand_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_systemCommand_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_systemCommand_pargs {
 public:


  virtual ~Dial_systemCommand_pargs() throw() {}

  const SysCommand::type* cmdType;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_systemCommand_result__isset {
  _Dial_systemCommand_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_systemCommand_result__isset;

class Dial_systemCommand_result {
 public:

  Dial_systemCommand_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_systemCommand_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_systemCommand_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_systemCommand_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_systemCommand_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_systemCommand_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_systemCommand_presult__isset {
  _Dial_systemCommand_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_systemCommand_presult__isset;

class Dial_systemCommand_presult {
 public:


  virtual ~Dial_systemCommand_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_systemCommand_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_addHealthGroup_args__isset {
  _Dial_addHealthGroup_args__isset() : groupName(false), policyName(false) {}
  bool groupName;
  bool policyName;
} _Dial_addHealthGroup_args__isset;

class Dial_addHealthGroup_args {
 public:

  Dial_addHealthGroup_args() : groupName(), policyName() {
  }

  virtual ~Dial_addHealthGroup_args() throw() {}

  std::string groupName;
  std::string policyName;

  _Dial_addHealthGroup_args__isset __isset;

  void __set_groupName(const std::string& val) {
    groupName = val;
  }

  void __set_policyName(const std::string& val) {
    policyName = val;
  }

  bool operator == (const Dial_addHealthGroup_args & rhs) const
  {
    if (!(groupName == rhs.groupName))
      return false;
    if (!(policyName == rhs.policyName))
      return false;
    return true;
  }
  bool operator != (const Dial_addHealthGroup_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addHealthGroup_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_addHealthGroup_pargs {
 public:


  virtual ~Dial_addHealthGroup_pargs() throw() {}

  const std::string* groupName;
  const std::string* policyName;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addHealthGroup_result__isset {
  _Dial_addHealthGroup_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addHealthGroup_result__isset;

class Dial_addHealthGroup_result {
 public:

  Dial_addHealthGroup_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_addHealthGroup_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_addHealthGroup_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_addHealthGroup_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_addHealthGroup_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addHealthGroup_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addHealthGroup_presult__isset {
  _Dial_addHealthGroup_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addHealthGroup_presult__isset;

class Dial_addHealthGroup_presult {
 public:


  virtual ~Dial_addHealthGroup_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_addHealthGroup_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_delHealthGroup_args__isset {
  _Dial_delHealthGroup_args__isset() : groupName(false), policyName(false) {}
  bool groupName;
  bool policyName;
} _Dial_delHealthGroup_args__isset;

class Dial_delHealthGroup_args {
 public:

  Dial_delHealthGroup_args() : groupName(), policyName() {
  }

  virtual ~Dial_delHealthGroup_args() throw() {}

  std::string groupName;
  std::string policyName;

  _Dial_delHealthGroup_args__isset __isset;

  void __set_groupName(const std::string& val) {
    groupName = val;
  }

  void __set_policyName(const std::string& val) {
    policyName = val;
  }

  bool operator == (const Dial_delHealthGroup_args & rhs) const
  {
    if (!(groupName == rhs.groupName))
      return false;
    if (!(policyName == rhs.policyName))
      return false;
    return true;
  }
  bool operator != (const Dial_delHealthGroup_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delHealthGroup_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_delHealthGroup_pargs {
 public:


  virtual ~Dial_delHealthGroup_pargs() throw() {}

  const std::string* groupName;
  const std::string* policyName;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delHealthGroup_result__isset {
  _Dial_delHealthGroup_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delHealthGroup_result__isset;

class Dial_delHealthGroup_result {
 public:

  Dial_delHealthGroup_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_delHealthGroup_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_delHealthGroup_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_delHealthGroup_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_delHealthGroup_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delHealthGroup_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delHealthGroup_presult__isset {
  _Dial_delHealthGroup_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delHealthGroup_presult__isset;

class Dial_delHealthGroup_presult {
 public:


  virtual ~Dial_delHealthGroup_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_delHealthGroup_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_addHealthRecord_args__isset {
  _Dial_addHealthRecord_args__isset() : groupName(false), records(false) {}
  bool groupName;
  bool records;
} _Dial_addHealthRecord_args__isset;

class Dial_addHealthRecord_args {
 public:

  Dial_addHealthRecord_args() : groupName() {
  }

  virtual ~Dial_addHealthRecord_args() throw() {}

  std::string groupName;
  std::vector<DialRecord>  records;

  _Dial_addHealthRecord_args__isset __isset;

  void __set_groupName(const std::string& val) {
    groupName = val;
  }

  void __set_records(const std::vector<DialRecord> & val) {
    records = val;
  }

  bool operator == (const Dial_addHealthRecord_args & rhs) const
  {
    if (!(groupName == rhs.groupName))
      return false;
    if (!(records == rhs.records))
      return false;
    return true;
  }
  bool operator != (const Dial_addHealthRecord_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addHealthRecord_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_addHealthRecord_pargs {
 public:


  virtual ~Dial_addHealthRecord_pargs() throw() {}

  const std::string* groupName;
  const std::vector<DialRecord> * records;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addHealthRecord_result__isset {
  _Dial_addHealthRecord_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addHealthRecord_result__isset;

class Dial_addHealthRecord_result {
 public:

  Dial_addHealthRecord_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_addHealthRecord_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_addHealthRecord_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_addHealthRecord_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_addHealthRecord_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addHealthRecord_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addHealthRecord_presult__isset {
  _Dial_addHealthRecord_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addHealthRecord_presult__isset;

class Dial_addHealthRecord_presult {
 public:


  virtual ~Dial_addHealthRecord_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_addHealthRecord_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_delHealthRecord_args__isset {
  _Dial_delHealthRecord_args__isset() : groupName(false), records(false) {}
  bool groupName;
  bool records;
} _Dial_delHealthRecord_args__isset;

class Dial_delHealthRecord_args {
 public:

  Dial_delHealthRecord_args() : groupName() {
  }

  virtual ~Dial_delHealthRecord_args() throw() {}

  std::string groupName;
  std::vector<DialRecord>  records;

  _Dial_delHealthRecord_args__isset __isset;

  void __set_groupName(const std::string& val) {
    groupName = val;
  }

  void __set_records(const std::vector<DialRecord> & val) {
    records = val;
  }

  bool operator == (const Dial_delHealthRecord_args & rhs) const
  {
    if (!(groupName == rhs.groupName))
      return false;
    if (!(records == rhs.records))
      return false;
    return true;
  }
  bool operator != (const Dial_delHealthRecord_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delHealthRecord_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_delHealthRecord_pargs {
 public:


  virtual ~Dial_delHealthRecord_pargs() throw() {}

  const std::string* groupName;
  const std::vector<DialRecord> * records;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delHealthRecord_result__isset {
  _Dial_delHealthRecord_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delHealthRecord_result__isset;

class Dial_delHealthRecord_result {
 public:

  Dial_delHealthRecord_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_delHealthRecord_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_delHealthRecord_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_delHealthRecord_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_delHealthRecord_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delHealthRecord_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delHealthRecord_presult__isset {
  _Dial_delHealthRecord_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delHealthRecord_presult__isset;

class Dial_delHealthRecord_presult {
 public:


  virtual ~Dial_delHealthRecord_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_delHealthRecord_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_addHealthPolicy_args__isset {
  _Dial_addHealthPolicy_args__isset() : policy(false) {}
  bool policy;
} _Dial_addHealthPolicy_args__isset;

class Dial_addHealthPolicy_args {
 public:

  Dial_addHealthPolicy_args() {
  }

  virtual ~Dial_addHealthPolicy_args() throw() {}

  HealthPolicyInfo policy;

  _Dial_addHealthPolicy_args__isset __isset;

  void __set_policy(const HealthPolicyInfo& val) {
    policy = val;
  }

  bool operator == (const Dial_addHealthPolicy_args & rhs) const
  {
    if (!(policy == rhs.policy))
      return false;
    return true;
  }
  bool operator != (const Dial_addHealthPolicy_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addHealthPolicy_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_addHealthPolicy_pargs {
 public:


  virtual ~Dial_addHealthPolicy_pargs() throw() {}

  const HealthPolicyInfo* policy;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addHealthPolicy_result__isset {
  _Dial_addHealthPolicy_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addHealthPolicy_result__isset;

class Dial_addHealthPolicy_result {
 public:

  Dial_addHealthPolicy_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_addHealthPolicy_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_addHealthPolicy_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_addHealthPolicy_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_addHealthPolicy_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addHealthPolicy_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addHealthPolicy_presult__isset {
  _Dial_addHealthPolicy_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addHealthPolicy_presult__isset;

class Dial_addHealthPolicy_presult {
 public:


  virtual ~Dial_addHealthPolicy_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_addHealthPolicy_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_modHealthPolicy_args__isset {
  _Dial_modHealthPolicy_args__isset() : policy(false) {}
  bool policy;
} _Dial_modHealthPolicy_args__isset;

class Dial_modHealthPolicy_args {
 public:

  Dial_modHealthPolicy_args() {
  }

  virtual ~Dial_modHealthPolicy_args() throw() {}

  HealthPolicyInfo policy;

  _Dial_modHealthPolicy_args__isset __isset;

  void __set_policy(const HealthPolicyInfo& val) {
    policy = val;
  }

  bool operator == (const Dial_modHealthPolicy_args & rhs) const
  {
    if (!(policy == rhs.policy))
      return false;
    return true;
  }
  bool operator != (const Dial_modHealthPolicy_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_modHealthPolicy_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_modHealthPolicy_pargs {
 public:


  virtual ~Dial_modHealthPolicy_pargs() throw() {}

  const HealthPolicyInfo* policy;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_modHealthPolicy_result__isset {
  _Dial_modHealthPolicy_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_modHealthPolicy_result__isset;

class Dial_modHealthPolicy_result {
 public:

  Dial_modHealthPolicy_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_modHealthPolicy_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_modHealthPolicy_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_modHealthPolicy_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_modHealthPolicy_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_modHealthPolicy_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_modHealthPolicy_presult__isset {
  _Dial_modHealthPolicy_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_modHealthPolicy_presult__isset;

class Dial_modHealthPolicy_presult {
 public:


  virtual ~Dial_modHealthPolicy_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_modHealthPolicy_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_delHealthPolicy_args__isset {
  _Dial_delHealthPolicy_args__isset() : policy(false) {}
  bool policy;
} _Dial_delHealthPolicy_args__isset;

class Dial_delHealthPolicy_args {
 public:

  Dial_delHealthPolicy_args() {
  }

  virtual ~Dial_delHealthPolicy_args() throw() {}

  HealthPolicyInfo policy;

  _Dial_delHealthPolicy_args__isset __isset;

  void __set_policy(const HealthPolicyInfo& val) {
    policy = val;
  }

  bool operator == (const Dial_delHealthPolicy_args & rhs) const
  {
    if (!(policy == rhs.policy))
      return false;
    return true;
  }
  bool operator != (const Dial_delHealthPolicy_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delHealthPolicy_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_delHealthPolicy_pargs {
 public:


  virtual ~Dial_delHealthPolicy_pargs() throw() {}

  const HealthPolicyInfo* policy;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delHealthPolicy_result__isset {
  _Dial_delHealthPolicy_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delHealthPolicy_result__isset;

class Dial_delHealthPolicy_result {
 public:

  Dial_delHealthPolicy_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_delHealthPolicy_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_delHealthPolicy_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_delHealthPolicy_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_delHealthPolicy_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delHealthPolicy_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delHealthPolicy_presult__isset {
  _Dial_delHealthPolicy_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delHealthPolicy_presult__isset;

class Dial_delHealthPolicy_presult {
 public:


  virtual ~Dial_delHealthPolicy_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_delHealthPolicy_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_addDialServer_args__isset {
  _Dial_addDialServer_args__isset() : rid(false), ip(false), typ(false) {}
  bool rid;
  bool ip;
  bool typ;
} _Dial_addDialServer_args__isset;

class Dial_addDialServer_args {
 public:

  Dial_addDialServer_args() : rid(), typ((DialServerType::type)0) {
  }

  virtual ~Dial_addDialServer_args() throw() {}

  ObjectId rid;
  IpAddr ip;
  DialServerType::type typ;

  _Dial_addDialServer_args__isset __isset;

  void __set_rid(const ObjectId& val) {
    rid = val;
  }

  void __set_ip(const IpAddr& val) {
    ip = val;
  }

  void __set_typ(const DialServerType::type val) {
    typ = val;
  }

  bool operator == (const Dial_addDialServer_args & rhs) const
  {
    if (!(rid == rhs.rid))
      return false;
    if (!(ip == rhs.ip))
      return false;
    if (!(typ == rhs.typ))
      return false;
    return true;
  }
  bool operator != (const Dial_addDialServer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addDialServer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_addDialServer_pargs {
 public:


  virtual ~Dial_addDialServer_pargs() throw() {}

  const ObjectId* rid;
  const IpAddr* ip;
  const DialServerType::type* typ;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addDialServer_result__isset {
  _Dial_addDialServer_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addDialServer_result__isset;

class Dial_addDialServer_result {
 public:

  Dial_addDialServer_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_addDialServer_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_addDialServer_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_addDialServer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_addDialServer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addDialServer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addDialServer_presult__isset {
  _Dial_addDialServer_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addDialServer_presult__isset;

class Dial_addDialServer_presult {
 public:


  virtual ~Dial_addDialServer_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_addDialServer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_delDialServer_args__isset {
  _Dial_delDialServer_args__isset() : rid(false) {}
  bool rid;
} _Dial_delDialServer_args__isset;

class Dial_delDialServer_args {
 public:

  Dial_delDialServer_args() : rid() {
  }

  virtual ~Dial_delDialServer_args() throw() {}

  ObjectId rid;

  _Dial_delDialServer_args__isset __isset;

  void __set_rid(const ObjectId& val) {
    rid = val;
  }

  bool operator == (const Dial_delDialServer_args & rhs) const
  {
    if (!(rid == rhs.rid))
      return false;
    return true;
  }
  bool operator != (const Dial_delDialServer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delDialServer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_delDialServer_pargs {
 public:


  virtual ~Dial_delDialServer_pargs() throw() {}

  const ObjectId* rid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delDialServer_result__isset {
  _Dial_delDialServer_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delDialServer_result__isset;

class Dial_delDialServer_result {
 public:

  Dial_delDialServer_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_delDialServer_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_delDialServer_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_delDialServer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_delDialServer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delDialServer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delDialServer_presult__isset {
  _Dial_delDialServer_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delDialServer_presult__isset;

class Dial_delDialServer_presult {
 public:


  virtual ~Dial_delDialServer_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_delDialServer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_addNginxGroup_args__isset {
  _Dial_addNginxGroup_args__isset() : groupName(false), policyName(false) {}
  bool groupName;
  bool policyName;
} _Dial_addNginxGroup_args__isset;

class Dial_addNginxGroup_args {
 public:

  Dial_addNginxGroup_args() : groupName(), policyName() {
  }

  virtual ~Dial_addNginxGroup_args() throw() {}

  std::string groupName;
  std::string policyName;

  _Dial_addNginxGroup_args__isset __isset;

  void __set_groupName(const std::string& val) {
    groupName = val;
  }

  void __set_policyName(const std::string& val) {
    policyName = val;
  }

  bool operator == (const Dial_addNginxGroup_args & rhs) const
  {
    if (!(groupName == rhs.groupName))
      return false;
    if (!(policyName == rhs.policyName))
      return false;
    return true;
  }
  bool operator != (const Dial_addNginxGroup_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addNginxGroup_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_addNginxGroup_pargs {
 public:


  virtual ~Dial_addNginxGroup_pargs() throw() {}

  const std::string* groupName;
  const std::string* policyName;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addNginxGroup_result__isset {
  _Dial_addNginxGroup_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addNginxGroup_result__isset;

class Dial_addNginxGroup_result {
 public:

  Dial_addNginxGroup_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_addNginxGroup_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_addNginxGroup_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_addNginxGroup_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_addNginxGroup_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addNginxGroup_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addNginxGroup_presult__isset {
  _Dial_addNginxGroup_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addNginxGroup_presult__isset;

class Dial_addNginxGroup_presult {
 public:


  virtual ~Dial_addNginxGroup_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_addNginxGroup_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_delNginxGroup_args__isset {
  _Dial_delNginxGroup_args__isset() : groupName(false), policyName(false) {}
  bool groupName;
  bool policyName;
} _Dial_delNginxGroup_args__isset;

class Dial_delNginxGroup_args {
 public:

  Dial_delNginxGroup_args() : groupName(), policyName() {
  }

  virtual ~Dial_delNginxGroup_args() throw() {}

  std::string groupName;
  std::string policyName;

  _Dial_delNginxGroup_args__isset __isset;

  void __set_groupName(const std::string& val) {
    groupName = val;
  }

  void __set_policyName(const std::string& val) {
    policyName = val;
  }

  bool operator == (const Dial_delNginxGroup_args & rhs) const
  {
    if (!(groupName == rhs.groupName))
      return false;
    if (!(policyName == rhs.policyName))
      return false;
    return true;
  }
  bool operator != (const Dial_delNginxGroup_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delNginxGroup_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_delNginxGroup_pargs {
 public:


  virtual ~Dial_delNginxGroup_pargs() throw() {}

  const std::string* groupName;
  const std::string* policyName;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delNginxGroup_result__isset {
  _Dial_delNginxGroup_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delNginxGroup_result__isset;

class Dial_delNginxGroup_result {
 public:

  Dial_delNginxGroup_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_delNginxGroup_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_delNginxGroup_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_delNginxGroup_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_delNginxGroup_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delNginxGroup_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delNginxGroup_presult__isset {
  _Dial_delNginxGroup_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delNginxGroup_presult__isset;

class Dial_delNginxGroup_presult {
 public:


  virtual ~Dial_delNginxGroup_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_delNginxGroup_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_addNginxServer_args__isset {
  _Dial_addNginxServer_args__isset() : groupName(false), servers(false) {}
  bool groupName;
  bool servers;
} _Dial_addNginxServer_args__isset;

class Dial_addNginxServer_args {
 public:

  Dial_addNginxServer_args() : groupName() {
  }

  virtual ~Dial_addNginxServer_args() throw() {}

  std::string groupName;
  std::vector<DialNginxServer>  servers;

  _Dial_addNginxServer_args__isset __isset;

  void __set_groupName(const std::string& val) {
    groupName = val;
  }

  void __set_servers(const std::vector<DialNginxServer> & val) {
    servers = val;
  }

  bool operator == (const Dial_addNginxServer_args & rhs) const
  {
    if (!(groupName == rhs.groupName))
      return false;
    if (!(servers == rhs.servers))
      return false;
    return true;
  }
  bool operator != (const Dial_addNginxServer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addNginxServer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_addNginxServer_pargs {
 public:


  virtual ~Dial_addNginxServer_pargs() throw() {}

  const std::string* groupName;
  const std::vector<DialNginxServer> * servers;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addNginxServer_result__isset {
  _Dial_addNginxServer_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addNginxServer_result__isset;

class Dial_addNginxServer_result {
 public:

  Dial_addNginxServer_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_addNginxServer_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_addNginxServer_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_addNginxServer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_addNginxServer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addNginxServer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addNginxServer_presult__isset {
  _Dial_addNginxServer_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addNginxServer_presult__isset;

class Dial_addNginxServer_presult {
 public:


  virtual ~Dial_addNginxServer_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_addNginxServer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_delNginxServer_args__isset {
  _Dial_delNginxServer_args__isset() : groupName(false), servers(false) {}
  bool groupName;
  bool servers;
} _Dial_delNginxServer_args__isset;

class Dial_delNginxServer_args {
 public:

  Dial_delNginxServer_args() : groupName() {
  }

  virtual ~Dial_delNginxServer_args() throw() {}

  std::string groupName;
  std::vector<DialNginxServer>  servers;

  _Dial_delNginxServer_args__isset __isset;

  void __set_groupName(const std::string& val) {
    groupName = val;
  }

  void __set_servers(const std::vector<DialNginxServer> & val) {
    servers = val;
  }

  bool operator == (const Dial_delNginxServer_args & rhs) const
  {
    if (!(groupName == rhs.groupName))
      return false;
    if (!(servers == rhs.servers))
      return false;
    return true;
  }
  bool operator != (const Dial_delNginxServer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delNginxServer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_delNginxServer_pargs {
 public:


  virtual ~Dial_delNginxServer_pargs() throw() {}

  const std::string* groupName;
  const std::vector<DialNginxServer> * servers;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delNginxServer_result__isset {
  _Dial_delNginxServer_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delNginxServer_result__isset;

class Dial_delNginxServer_result {
 public:

  Dial_delNginxServer_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_delNginxServer_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_delNginxServer_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_delNginxServer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_delNginxServer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delNginxServer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delNginxServer_presult__isset {
  _Dial_delNginxServer_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delNginxServer_presult__isset;

class Dial_delNginxServer_presult {
 public:


  virtual ~Dial_delNginxServer_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_delNginxServer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Dial_heartBeat_args {
 public:

  Dial_heartBeat_args() {
  }

  virtual ~Dial_heartBeat_args() throw() {}


  bool operator == (const Dial_heartBeat_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Dial_heartBeat_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_heartBeat_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_heartBeat_pargs {
 public:


  virtual ~Dial_heartBeat_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_heartBeat_result__isset {
  _Dial_heartBeat_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_heartBeat_result__isset;

class Dial_heartBeat_result {
 public:

  Dial_heartBeat_result() {
  }

  virtual ~Dial_heartBeat_result() throw() {}

  HeartBeatState success;
  Xception ex;

  _Dial_heartBeat_result__isset __isset;

  void __set_success(const HeartBeatState& val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_heartBeat_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_heartBeat_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_heartBeat_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_heartBeat_presult__isset {
  _Dial_heartBeat_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_heartBeat_presult__isset;

class Dial_heartBeat_presult {
 public:


  virtual ~Dial_heartBeat_presult() throw() {}

  HeartBeatState* success;
  Xception ex;

  _Dial_heartBeat_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_setServerState_args__isset {
  _Dial_setServerState_args__isset() : enable(false) {}
  bool enable;
} _Dial_setServerState_args__isset;

class Dial_setServerState_args {
 public:

  Dial_setServerState_args() : enable(0) {
  }

  virtual ~Dial_setServerState_args() throw() {}

  bool enable;

  _Dial_setServerState_args__isset __isset;

  void __set_enable(const bool val) {
    enable = val;
  }

  bool operator == (const Dial_setServerState_args & rhs) const
  {
    if (!(enable == rhs.enable))
      return false;
    return true;
  }
  bool operator != (const Dial_setServerState_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_setServerState_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_setServerState_pargs {
 public:


  virtual ~Dial_setServerState_pargs() throw() {}

  const bool* enable;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_setServerState_result__isset {
  _Dial_setServerState_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_setServerState_result__isset;

class Dial_setServerState_result {
 public:

  Dial_setServerState_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_setServerState_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_setServerState_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_setServerState_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_setServerState_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_setServerState_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_setServerState_presult__isset {
  _Dial_setServerState_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_setServerState_presult__isset;

class Dial_setServerState_presult {
 public:


  virtual ~Dial_setServerState_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_setServerState_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_addSnmpGroupInfo_args__isset {
  _Dial_addSnmpGroupInfo_args__isset() : snmp(false) {}
  bool snmp;
} _Dial_addSnmpGroupInfo_args__isset;

class Dial_addSnmpGroupInfo_args {
 public:

  Dial_addSnmpGroupInfo_args() {
  }

  virtual ~Dial_addSnmpGroupInfo_args() throw() {}

  SnmpGroupInfo snmp;

  _Dial_addSnmpGroupInfo_args__isset __isset;

  void __set_snmp(const SnmpGroupInfo& val) {
    snmp = val;
  }

  bool operator == (const Dial_addSnmpGroupInfo_args & rhs) const
  {
    if (!(snmp == rhs.snmp))
      return false;
    return true;
  }
  bool operator != (const Dial_addSnmpGroupInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addSnmpGroupInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_addSnmpGroupInfo_pargs {
 public:


  virtual ~Dial_addSnmpGroupInfo_pargs() throw() {}

  const SnmpGroupInfo* snmp;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addSnmpGroupInfo_result__isset {
  _Dial_addSnmpGroupInfo_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addSnmpGroupInfo_result__isset;

class Dial_addSnmpGroupInfo_result {
 public:

  Dial_addSnmpGroupInfo_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_addSnmpGroupInfo_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_addSnmpGroupInfo_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_addSnmpGroupInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_addSnmpGroupInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addSnmpGroupInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addSnmpGroupInfo_presult__isset {
  _Dial_addSnmpGroupInfo_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addSnmpGroupInfo_presult__isset;

class Dial_addSnmpGroupInfo_presult {
 public:


  virtual ~Dial_addSnmpGroupInfo_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_addSnmpGroupInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_delSnmpGroupInfo_args__isset {
  _Dial_delSnmpGroupInfo_args__isset() : snmp(false) {}
  bool snmp;
} _Dial_delSnmpGroupInfo_args__isset;

class Dial_delSnmpGroupInfo_args {
 public:

  Dial_delSnmpGroupInfo_args() : snmp() {
  }

  virtual ~Dial_delSnmpGroupInfo_args() throw() {}

  std::string snmp;

  _Dial_delSnmpGroupInfo_args__isset __isset;

  void __set_snmp(const std::string& val) {
    snmp = val;
  }

  bool operator == (const Dial_delSnmpGroupInfo_args & rhs) const
  {
    if (!(snmp == rhs.snmp))
      return false;
    return true;
  }
  bool operator != (const Dial_delSnmpGroupInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delSnmpGroupInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_delSnmpGroupInfo_pargs {
 public:


  virtual ~Dial_delSnmpGroupInfo_pargs() throw() {}

  const std::string* snmp;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delSnmpGroupInfo_result__isset {
  _Dial_delSnmpGroupInfo_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delSnmpGroupInfo_result__isset;

class Dial_delSnmpGroupInfo_result {
 public:

  Dial_delSnmpGroupInfo_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_delSnmpGroupInfo_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_delSnmpGroupInfo_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_delSnmpGroupInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_delSnmpGroupInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delSnmpGroupInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delSnmpGroupInfo_presult__isset {
  _Dial_delSnmpGroupInfo_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delSnmpGroupInfo_presult__isset;

class Dial_delSnmpGroupInfo_presult {
 public:


  virtual ~Dial_delSnmpGroupInfo_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_delSnmpGroupInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_addSnmpProcessInfo_args__isset {
  _Dial_addSnmpProcessInfo_args__isset() : snmp(false), processname(false) {}
  bool snmp;
  bool processname;
} _Dial_addSnmpProcessInfo_args__isset;

class Dial_addSnmpProcessInfo_args {
 public:

  Dial_addSnmpProcessInfo_args() : snmp(), processname() {
  }

  virtual ~Dial_addSnmpProcessInfo_args() throw() {}

  std::string snmp;
  std::string processname;

  _Dial_addSnmpProcessInfo_args__isset __isset;

  void __set_snmp(const std::string& val) {
    snmp = val;
  }

  void __set_processname(const std::string& val) {
    processname = val;
  }

  bool operator == (const Dial_addSnmpProcessInfo_args & rhs) const
  {
    if (!(snmp == rhs.snmp))
      return false;
    if (!(processname == rhs.processname))
      return false;
    return true;
  }
  bool operator != (const Dial_addSnmpProcessInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addSnmpProcessInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_addSnmpProcessInfo_pargs {
 public:


  virtual ~Dial_addSnmpProcessInfo_pargs() throw() {}

  const std::string* snmp;
  const std::string* processname;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addSnmpProcessInfo_result__isset {
  _Dial_addSnmpProcessInfo_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addSnmpProcessInfo_result__isset;

class Dial_addSnmpProcessInfo_result {
 public:

  Dial_addSnmpProcessInfo_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_addSnmpProcessInfo_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_addSnmpProcessInfo_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_addSnmpProcessInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_addSnmpProcessInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addSnmpProcessInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addSnmpProcessInfo_presult__isset {
  _Dial_addSnmpProcessInfo_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addSnmpProcessInfo_presult__isset;

class Dial_addSnmpProcessInfo_presult {
 public:


  virtual ~Dial_addSnmpProcessInfo_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_addSnmpProcessInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_delSnmpProcessInfo_args__isset {
  _Dial_delSnmpProcessInfo_args__isset() : snmp(false), processname(false) {}
  bool snmp;
  bool processname;
} _Dial_delSnmpProcessInfo_args__isset;

class Dial_delSnmpProcessInfo_args {
 public:

  Dial_delSnmpProcessInfo_args() : snmp(), processname() {
  }

  virtual ~Dial_delSnmpProcessInfo_args() throw() {}

  std::string snmp;
  std::string processname;

  _Dial_delSnmpProcessInfo_args__isset __isset;

  void __set_snmp(const std::string& val) {
    snmp = val;
  }

  void __set_processname(const std::string& val) {
    processname = val;
  }

  bool operator == (const Dial_delSnmpProcessInfo_args & rhs) const
  {
    if (!(snmp == rhs.snmp))
      return false;
    if (!(processname == rhs.processname))
      return false;
    return true;
  }
  bool operator != (const Dial_delSnmpProcessInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delSnmpProcessInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_delSnmpProcessInfo_pargs {
 public:


  virtual ~Dial_delSnmpProcessInfo_pargs() throw() {}

  const std::string* snmp;
  const std::string* processname;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delSnmpProcessInfo_result__isset {
  _Dial_delSnmpProcessInfo_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delSnmpProcessInfo_result__isset;

class Dial_delSnmpProcessInfo_result {
 public:

  Dial_delSnmpProcessInfo_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_delSnmpProcessInfo_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_delSnmpProcessInfo_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_delSnmpProcessInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_delSnmpProcessInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delSnmpProcessInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delSnmpProcessInfo_presult__isset {
  _Dial_delSnmpProcessInfo_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delSnmpProcessInfo_presult__isset;

class Dial_delSnmpProcessInfo_presult {
 public:


  virtual ~Dial_delSnmpProcessInfo_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_delSnmpProcessInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_addIpSec_args__isset {
  _Dial_addIpSec_args__isset() : ipsec(false), interval(false) {}
  bool ipsec;
  bool interval;
} _Dial_addIpSec_args__isset;

class Dial_addIpSec_args {
 public:

  Dial_addIpSec_args() : interval(0) {
  }

  virtual ~Dial_addIpSec_args() throw() {}

  SysIpSec ipsec;
  int32_t interval;

  _Dial_addIpSec_args__isset __isset;

  void __set_ipsec(const SysIpSec& val) {
    ipsec = val;
  }

  void __set_interval(const int32_t val) {
    interval = val;
  }

  bool operator == (const Dial_addIpSec_args & rhs) const
  {
    if (!(ipsec == rhs.ipsec))
      return false;
    if (!(interval == rhs.interval))
      return false;
    return true;
  }
  bool operator != (const Dial_addIpSec_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addIpSec_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_addIpSec_pargs {
 public:


  virtual ~Dial_addIpSec_pargs() throw() {}

  const SysIpSec* ipsec;
  const int32_t* interval;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addIpSec_result__isset {
  _Dial_addIpSec_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addIpSec_result__isset;

class Dial_addIpSec_result {
 public:

  Dial_addIpSec_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_addIpSec_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_addIpSec_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_addIpSec_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_addIpSec_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addIpSec_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addIpSec_presult__isset {
  _Dial_addIpSec_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addIpSec_presult__isset;

class Dial_addIpSec_presult {
 public:


  virtual ~Dial_addIpSec_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_addIpSec_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_delIpSec_args__isset {
  _Dial_delIpSec_args__isset() : ipsecid(false) {}
  bool ipsecid;
} _Dial_delIpSec_args__isset;

class Dial_delIpSec_args {
 public:

  Dial_delIpSec_args() : ipsecid() {
  }

  virtual ~Dial_delIpSec_args() throw() {}

  std::string ipsecid;

  _Dial_delIpSec_args__isset __isset;

  void __set_ipsecid(const std::string& val) {
    ipsecid = val;
  }

  bool operator == (const Dial_delIpSec_args & rhs) const
  {
    if (!(ipsecid == rhs.ipsecid))
      return false;
    return true;
  }
  bool operator != (const Dial_delIpSec_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delIpSec_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_delIpSec_pargs {
 public:


  virtual ~Dial_delIpSec_pargs() throw() {}

  const std::string* ipsecid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delIpSec_result__isset {
  _Dial_delIpSec_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delIpSec_result__isset;

class Dial_delIpSec_result {
 public:

  Dial_delIpSec_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_delIpSec_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_delIpSec_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_delIpSec_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_delIpSec_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delIpSec_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delIpSec_presult__isset {
  _Dial_delIpSec_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delIpSec_presult__isset;

class Dial_delIpSec_presult {
 public:


  virtual ~Dial_delIpSec_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_delIpSec_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_addDcInfo_args__isset {
  _Dial_addDcInfo_args__isset() : dc(false) {}
  bool dc;
} _Dial_addDcInfo_args__isset;

class Dial_addDcInfo_args {
 public:

  Dial_addDcInfo_args() {
  }

  virtual ~Dial_addDcInfo_args() throw() {}

  DcInfo dc;

  _Dial_addDcInfo_args__isset __isset;

  void __set_dc(const DcInfo& val) {
    dc = val;
  }

  bool operator == (const Dial_addDcInfo_args & rhs) const
  {
    if (!(dc == rhs.dc))
      return false;
    return true;
  }
  bool operator != (const Dial_addDcInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addDcInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_addDcInfo_pargs {
 public:


  virtual ~Dial_addDcInfo_pargs() throw() {}

  const DcInfo* dc;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addDcInfo_result__isset {
  _Dial_addDcInfo_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addDcInfo_result__isset;

class Dial_addDcInfo_result {
 public:

  Dial_addDcInfo_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_addDcInfo_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_addDcInfo_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_addDcInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_addDcInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_addDcInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_addDcInfo_presult__isset {
  _Dial_addDcInfo_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_addDcInfo_presult__isset;

class Dial_addDcInfo_presult {
 public:


  virtual ~Dial_addDcInfo_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_addDcInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Dial_delDcInfo_args__isset {
  _Dial_delDcInfo_args__isset() : id(false) {}
  bool id;
} _Dial_delDcInfo_args__isset;

class Dial_delDcInfo_args {
 public:

  Dial_delDcInfo_args() : id() {
  }

  virtual ~Dial_delDcInfo_args() throw() {}

  std::string id;

  _Dial_delDcInfo_args__isset __isset;

  void __set_id(const std::string& val) {
    id = val;
  }

  bool operator == (const Dial_delDcInfo_args & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    return true;
  }
  bool operator != (const Dial_delDcInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delDcInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Dial_delDcInfo_pargs {
 public:


  virtual ~Dial_delDcInfo_pargs() throw() {}

  const std::string* id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delDcInfo_result__isset {
  _Dial_delDcInfo_result__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delDcInfo_result__isset;

class Dial_delDcInfo_result {
 public:

  Dial_delDcInfo_result() : success((RetCode::type)0) {
  }

  virtual ~Dial_delDcInfo_result() throw() {}

  RetCode::type success;
  Xception ex;

  _Dial_delDcInfo_result__isset __isset;

  void __set_success(const RetCode::type val) {
    success = val;
  }

  void __set_ex(const Xception& val) {
    ex = val;
  }

  bool operator == (const Dial_delDcInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const Dial_delDcInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Dial_delDcInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Dial_delDcInfo_presult__isset {
  _Dial_delDcInfo_presult__isset() : success(false), ex(false) {}
  bool success;
  bool ex;
} _Dial_delDcInfo_presult__isset;

class Dial_delDcInfo_presult {
 public:


  virtual ~Dial_delDcInfo_presult() throw() {}

  RetCode::type* success;
  Xception ex;

  _Dial_delDcInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class DialClient : virtual public DialIf {
 public:
  DialClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  DialClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  RetCode::type systemCommand(const SysCommand::type cmdType);
  void send_systemCommand(const SysCommand::type cmdType);
  RetCode::type recv_systemCommand();
  RetCode::type addHealthGroup(const std::string& groupName, const std::string& policyName);
  void send_addHealthGroup(const std::string& groupName, const std::string& policyName);
  RetCode::type recv_addHealthGroup();
  RetCode::type delHealthGroup(const std::string& groupName, const std::string& policyName);
  void send_delHealthGroup(const std::string& groupName, const std::string& policyName);
  RetCode::type recv_delHealthGroup();
  RetCode::type addHealthRecord(const std::string& groupName, const std::vector<DialRecord> & records);
  void send_addHealthRecord(const std::string& groupName, const std::vector<DialRecord> & records);
  RetCode::type recv_addHealthRecord();
  RetCode::type delHealthRecord(const std::string& groupName, const std::vector<DialRecord> & records);
  void send_delHealthRecord(const std::string& groupName, const std::vector<DialRecord> & records);
  RetCode::type recv_delHealthRecord();
  RetCode::type addHealthPolicy(const HealthPolicyInfo& policy);
  void send_addHealthPolicy(const HealthPolicyInfo& policy);
  RetCode::type recv_addHealthPolicy();
  RetCode::type modHealthPolicy(const HealthPolicyInfo& policy);
  void send_modHealthPolicy(const HealthPolicyInfo& policy);
  RetCode::type recv_modHealthPolicy();
  RetCode::type delHealthPolicy(const HealthPolicyInfo& policy);
  void send_delHealthPolicy(const HealthPolicyInfo& policy);
  RetCode::type recv_delHealthPolicy();
  RetCode::type addDialServer(const ObjectId& rid, const IpAddr& ip, const DialServerType::type typ);
  void send_addDialServer(const ObjectId& rid, const IpAddr& ip, const DialServerType::type typ);
  RetCode::type recv_addDialServer();
  RetCode::type delDialServer(const ObjectId& rid);
  void send_delDialServer(const ObjectId& rid);
  RetCode::type recv_delDialServer();
  RetCode::type addNginxGroup(const std::string& groupName, const std::string& policyName);
  void send_addNginxGroup(const std::string& groupName, const std::string& policyName);
  RetCode::type recv_addNginxGroup();
  RetCode::type delNginxGroup(const std::string& groupName, const std::string& policyName);
  void send_delNginxGroup(const std::string& groupName, const std::string& policyName);
  RetCode::type recv_delNginxGroup();
  RetCode::type addNginxServer(const std::string& groupName, const std::vector<DialNginxServer> & servers);
  void send_addNginxServer(const std::string& groupName, const std::vector<DialNginxServer> & servers);
  RetCode::type recv_addNginxServer();
  RetCode::type delNginxServer(const std::string& groupName, const std::vector<DialNginxServer> & servers);
  void send_delNginxServer(const std::string& groupName, const std::vector<DialNginxServer> & servers);
  RetCode::type recv_delNginxServer();
  void heartBeat(HeartBeatState& _return);
  void send_heartBeat();
  void recv_heartBeat(HeartBeatState& _return);
  RetCode::type setServerState(const bool enable);
  void send_setServerState(const bool enable);
  RetCode::type recv_setServerState();
  RetCode::type addSnmpGroupInfo(const SnmpGroupInfo& snmp);
  void send_addSnmpGroupInfo(const SnmpGroupInfo& snmp);
  RetCode::type recv_addSnmpGroupInfo();
  RetCode::type delSnmpGroupInfo(const std::string& snmp);
  void send_delSnmpGroupInfo(const std::string& snmp);
  RetCode::type recv_delSnmpGroupInfo();
  RetCode::type addSnmpProcessInfo(const std::string& snmp, const std::string& processname);
  void send_addSnmpProcessInfo(const std::string& snmp, const std::string& processname);
  RetCode::type recv_addSnmpProcessInfo();
  RetCode::type delSnmpProcessInfo(const std::string& snmp, const std::string& processname);
  void send_delSnmpProcessInfo(const std::string& snmp, const std::string& processname);
  RetCode::type recv_delSnmpProcessInfo();
  RetCode::type addIpSec(const SysIpSec& ipsec, const int32_t interval);
  void send_addIpSec(const SysIpSec& ipsec, const int32_t interval);
  RetCode::type recv_addIpSec();
  RetCode::type delIpSec(const std::string& ipsecid);
  void send_delIpSec(const std::string& ipsecid);
  RetCode::type recv_delIpSec();
  RetCode::type addDcInfo(const DcInfo& dc);
  void send_addDcInfo(const DcInfo& dc);
  RetCode::type recv_addDcInfo();
  RetCode::type delDcInfo(const std::string& id);
  void send_delDcInfo(const std::string& id);
  RetCode::type recv_delDcInfo();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class DialProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<DialIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (DialProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_systemCommand(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_addHealthGroup(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delHealthGroup(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_addHealthRecord(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delHealthRecord(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_addHealthPolicy(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_modHealthPolicy(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delHealthPolicy(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_addDialServer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delDialServer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_addNginxGroup(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delNginxGroup(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_addNginxServer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delNginxServer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_heartBeat(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_setServerState(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_addSnmpGroupInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delSnmpGroupInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_addSnmpProcessInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delSnmpProcessInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_addIpSec(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delIpSec(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_addDcInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delDcInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  DialProcessor(boost::shared_ptr<DialIf> iface) :
    iface_(iface) {
    processMap_["systemCommand"] = &DialProcessor::process_systemCommand;
    processMap_["addHealthGroup"] = &DialProcessor::process_addHealthGroup;
    processMap_["delHealthGroup"] = &DialProcessor::process_delHealthGroup;
    processMap_["addHealthRecord"] = &DialProcessor::process_addHealthRecord;
    processMap_["delHealthRecord"] = &DialProcessor::process_delHealthRecord;
    processMap_["addHealthPolicy"] = &DialProcessor::process_addHealthPolicy;
    processMap_["modHealthPolicy"] = &DialProcessor::process_modHealthPolicy;
    processMap_["delHealthPolicy"] = &DialProcessor::process_delHealthPolicy;
    processMap_["addDialServer"] = &DialProcessor::process_addDialServer;
    processMap_["delDialServer"] = &DialProcessor::process_delDialServer;
    processMap_["addNginxGroup"] = &DialProcessor::process_addNginxGroup;
    processMap_["delNginxGroup"] = &DialProcessor::process_delNginxGroup;
    processMap_["addNginxServer"] = &DialProcessor::process_addNginxServer;
    processMap_["delNginxServer"] = &DialProcessor::process_delNginxServer;
    processMap_["heartBeat"] = &DialProcessor::process_heartBeat;
    processMap_["setServerState"] = &DialProcessor::process_setServerState;
    processMap_["addSnmpGroupInfo"] = &DialProcessor::process_addSnmpGroupInfo;
    processMap_["delSnmpGroupInfo"] = &DialProcessor::process_delSnmpGroupInfo;
    processMap_["addSnmpProcessInfo"] = &DialProcessor::process_addSnmpProcessInfo;
    processMap_["delSnmpProcessInfo"] = &DialProcessor::process_delSnmpProcessInfo;
    processMap_["addIpSec"] = &DialProcessor::process_addIpSec;
    processMap_["delIpSec"] = &DialProcessor::process_delIpSec;
    processMap_["addDcInfo"] = &DialProcessor::process_addDcInfo;
    processMap_["delDcInfo"] = &DialProcessor::process_delDcInfo;
  }

  virtual ~DialProcessor() {}
};

class DialProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  DialProcessorFactory(const ::boost::shared_ptr< DialIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< DialIfFactory > handlerFactory_;
};

class DialMultiface : virtual public DialIf {
 public:
  DialMultiface(std::vector<boost::shared_ptr<DialIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~DialMultiface() {}
 protected:
  std::vector<boost::shared_ptr<DialIf> > ifaces_;
  DialMultiface() {}
  void add(boost::shared_ptr<DialIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  RetCode::type systemCommand(const SysCommand::type cmdType) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->systemCommand(cmdType);
    }
    return ifaces_[i]->systemCommand(cmdType);
  }

  RetCode::type addHealthGroup(const std::string& groupName, const std::string& policyName) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addHealthGroup(groupName, policyName);
    }
    return ifaces_[i]->addHealthGroup(groupName, policyName);
  }

  RetCode::type delHealthGroup(const std::string& groupName, const std::string& policyName) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->delHealthGroup(groupName, policyName);
    }
    return ifaces_[i]->delHealthGroup(groupName, policyName);
  }

  RetCode::type addHealthRecord(const std::string& groupName, const std::vector<DialRecord> & records) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addHealthRecord(groupName, records);
    }
    return ifaces_[i]->addHealthRecord(groupName, records);
  }

  RetCode::type delHealthRecord(const std::string& groupName, const std::vector<DialRecord> & records) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->delHealthRecord(groupName, records);
    }
    return ifaces_[i]->delHealthRecord(groupName, records);
  }

  RetCode::type addHealthPolicy(const HealthPolicyInfo& policy) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addHealthPolicy(policy);
    }
    return ifaces_[i]->addHealthPolicy(policy);
  }

  RetCode::type modHealthPolicy(const HealthPolicyInfo& policy) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->modHealthPolicy(policy);
    }
    return ifaces_[i]->modHealthPolicy(policy);
  }

  RetCode::type delHealthPolicy(const HealthPolicyInfo& policy) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->delHealthPolicy(policy);
    }
    return ifaces_[i]->delHealthPolicy(policy);
  }

  RetCode::type addDialServer(const ObjectId& rid, const IpAddr& ip, const DialServerType::type typ) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addDialServer(rid, ip, typ);
    }
    return ifaces_[i]->addDialServer(rid, ip, typ);
  }

  RetCode::type delDialServer(const ObjectId& rid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->delDialServer(rid);
    }
    return ifaces_[i]->delDialServer(rid);
  }

  RetCode::type addNginxGroup(const std::string& groupName, const std::string& policyName) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addNginxGroup(groupName, policyName);
    }
    return ifaces_[i]->addNginxGroup(groupName, policyName);
  }

  RetCode::type delNginxGroup(const std::string& groupName, const std::string& policyName) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->delNginxGroup(groupName, policyName);
    }
    return ifaces_[i]->delNginxGroup(groupName, policyName);
  }

  RetCode::type addNginxServer(const std::string& groupName, const std::vector<DialNginxServer> & servers) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addNginxServer(groupName, servers);
    }
    return ifaces_[i]->addNginxServer(groupName, servers);
  }

  RetCode::type delNginxServer(const std::string& groupName, const std::vector<DialNginxServer> & servers) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->delNginxServer(groupName, servers);
    }
    return ifaces_[i]->delNginxServer(groupName, servers);
  }

  void heartBeat(HeartBeatState& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->heartBeat(_return);
    }
    ifaces_[i]->heartBeat(_return);
    return;
  }

  RetCode::type setServerState(const bool enable) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->setServerState(enable);
    }
    return ifaces_[i]->setServerState(enable);
  }

  RetCode::type addSnmpGroupInfo(const SnmpGroupInfo& snmp) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addSnmpGroupInfo(snmp);
    }
    return ifaces_[i]->addSnmpGroupInfo(snmp);
  }

  RetCode::type delSnmpGroupInfo(const std::string& snmp) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->delSnmpGroupInfo(snmp);
    }
    return ifaces_[i]->delSnmpGroupInfo(snmp);
  }

  RetCode::type addSnmpProcessInfo(const std::string& snmp, const std::string& processname) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addSnmpProcessInfo(snmp, processname);
    }
    return ifaces_[i]->addSnmpProcessInfo(snmp, processname);
  }

  RetCode::type delSnmpProcessInfo(const std::string& snmp, const std::string& processname) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->delSnmpProcessInfo(snmp, processname);
    }
    return ifaces_[i]->delSnmpProcessInfo(snmp, processname);
  }

  RetCode::type addIpSec(const SysIpSec& ipsec, const int32_t interval) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addIpSec(ipsec, interval);
    }
    return ifaces_[i]->addIpSec(ipsec, interval);
  }

  RetCode::type delIpSec(const std::string& ipsecid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->delIpSec(ipsecid);
    }
    return ifaces_[i]->delIpSec(ipsecid);
  }

  RetCode::type addDcInfo(const DcInfo& dc) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addDcInfo(dc);
    }
    return ifaces_[i]->addDcInfo(dc);
  }

  RetCode::type delDcInfo(const std::string& id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->delDcInfo(id);
    }
    return ifaces_[i]->delDcInfo(id);
  }

};

}}}} // namespace

#endif
