/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dialrpc_CONSTANTS_H
#define dialrpc_CONSTANTS_H

#include "dialrpc_types.h"

namespace rpc { namespace dial { namespace yamutech { namespace com {

class dialrpcConstants {
 public:
  dialrpcConstants();

};

extern const dialrpcConstants g_dialrpc_constants;

}}}} // namespace

#endif
