/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dialrpc_constants.h"

namespace rpc { namespace dial { namespace yamutech { namespace com {

const dialrpcConstants g_dialrpc_constants;

dialrpcConstants::dialrpcConstants() {
}

}}}} // namespace

